const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Behaviors.Anchor,
		C3.Behaviors.MoveTo,
		C3.Behaviors.LOS,
		C3.Plugins.Text,
		C3.Behaviors.Physics,
		C3.Plugins.Particles,
		C3.Behaviors.Bullet,
		C3.Behaviors.Persist,
		C3.Plugins.Mouse,
		C3.Behaviors.Orbit,
		C3.Plugins.progressbar,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Behaviors.MoveTo.Acts.Stop,
		C3.Behaviors.MoveTo.Acts.SetEnabled,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Exps.BBoxMidX,
		C3.Plugins.Sprite.Exps.BBoxMidY,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.progressbar.Acts.SetProgress,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Touch.Cnds.OnDoubleTapGesture
	];
};
self.C3_JsPropNameTable = [
	{Твёрдый: 0},
	{Платформер: 0},
	{СледитьЗа: 0},
	{Спрайт: 0},
	{Спрайт2: 0},
	{Клавиатура: 0},
	{Тач: 0},
	{Аудио: 0},
	{Спрайт3: 0},
	{Спрайт4: 0},
	{Якорь: 0},
	{Спрайт5: 0},
	{ДвижениеК: 0},
	{ПолеЗрения: 0},
	{Спрайт6: 0},
	{Текст: 0},
	{Физика: 0},
	{Спрайт7: 0},
	{Спрайт8: 0},
	{Частицы: 0},
	{Частицы2: 0},
	{Спрайт9: 0},
	{Спрайт10: 0},
	{Спрайт11: 0},
	{Спрайт12: 0},
	{Спрайт13: 0},
	{Спрайт14: 0},
	{Спрайт15: 0},
	{ж: 0},
	{Спрайт16: 0},
	{Пуля: 0},
	{Спрайт17: 0},
	{Спрайт19: 0},
	{Запечатлеть: 0},
	{Спрайт20: 0},
	{Спрайт21: 0},
	{Спрайт22: 0},
	{Спрайт18: 0},
	{Мышь: 0},
	{Спрайт23: 0},
	{Спрайт24: 0},
	{Спрайт25: 0},
	{Орбита: 0},
	{Спрайт26: 0},
	{Текст2: 0},
	{Спрайт27: 0},
	{Спрайт28: 0},
	{Спрайт29: 0},
	{Спрайт30: 0},
	{Индикатор: 0},
	{Частицы3: 0},
	{Спрайт31: 0},
	{Текст3: 0},
	{Спрайт32: 0},
	{Спрайт33: 0},
	{схемы: 0},
	{дч: 0},
	{жизьки: 0}
];

self.InstanceType = {
	Спрайт: class extends self.ISpriteInstance {},
	Спрайт2: class extends self.ISpriteInstance {},
	Клавиатура: class extends self.IInstance {},
	Тач: class extends self.IInstance {},
	Аудио: class extends self.IInstance {},
	Спрайт3: class extends self.ISpriteInstance {},
	Спрайт4: class extends self.ISpriteInstance {},
	Спрайт5: class extends self.ISpriteInstance {},
	Спрайт6: class extends self.ISpriteInstance {},
	Текст: class extends self.ITextInstance {},
	Спрайт7: class extends self.ISpriteInstance {},
	Спрайт8: class extends self.ISpriteInstance {},
	Частицы: class extends self.IParticlesInstance {},
	Частицы2: class extends self.IParticlesInstance {},
	Спрайт9: class extends self.ISpriteInstance {},
	Спрайт10: class extends self.ISpriteInstance {},
	Спрайт11: class extends self.ISpriteInstance {},
	Спрайт12: class extends self.ISpriteInstance {},
	Спрайт13: class extends self.ISpriteInstance {},
	Спрайт14: class extends self.ISpriteInstance {},
	Спрайт15: class extends self.ISpriteInstance {},
	Спрайт16: class extends self.ISpriteInstance {},
	Спрайт17: class extends self.ISpriteInstance {},
	Спрайт19: class extends self.ISpriteInstance {},
	Спрайт20: class extends self.ISpriteInstance {},
	Спрайт21: class extends self.ISpriteInstance {},
	Спрайт22: class extends self.ISpriteInstance {},
	Спрайт18: class extends self.ISpriteInstance {},
	Мышь: class extends self.IInstance {},
	Спрайт23: class extends self.ISpriteInstance {},
	Спрайт24: class extends self.ISpriteInstance {},
	Спрайт25: class extends self.ISpriteInstance {},
	Спрайт26: class extends self.ISpriteInstance {},
	Текст2: class extends self.ITextInstance {},
	Спрайт27: class extends self.ISpriteInstance {},
	Спрайт28: class extends self.ISpriteInstance {},
	Спрайт29: class extends self.ISpriteInstance {},
	Спрайт30: class extends self.ISpriteInstance {},
	Индикатор: class extends self.IProgressBarInstance {},
	Частицы3: class extends self.IParticlesInstance {},
	Спрайт31: class extends self.ISpriteInstance {},
	Текст3: class extends self.ITextInstance {},
	Спрайт32: class extends self.ISpriteInstance {},
	Спрайт33: class extends self.ISpriteInstance {}
}